INITIAL_ALL = 'all'

FIELD_MODEL_LABEL = 'field_model'
PERCENTAGE_LABEL = 'percentage'
CHART_DATA = {1: {'chart_label': 'New Construction',
                  'criteria': {'field_name': 'new_construct_year', 'value': None},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District', 'No New Construction Made', 'New Construction Made']
                  },
              2: {'chart_label':  'Construction Made Before 2000',
                  'criteria': {'field_name': 'new_construct_year', 'value': 2000, 'lt_operator': True},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'Construction Made Before 2000',
                                        'Construction Made After 2000']},
              3: {'chart_label':  'No School Meetings',
                  'criteria': {'field_name': 'sc_meetings', 'value': None},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District', 'No School Meetings Conducted',
                                        'School Meetings Conducted']
                  },
              4: {'chart_label':  'Less than 10 School Meetings',
                  'criteria': {'field_name': 'sc_meetings', 'value': 10, 'lt_operator': True},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'Less than 10 School Meetings Conducted',
                                        'More than 10 School Meetings Conducted']
                  },
              5: {'chart_label':  'No School Women',
                  'criteria': {'field_name': 'sc_women', 'value': None},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'No Women in Schools',
                                        'Women in Schools']
                  },
              6: {'chart_label': 'No School Men',
                'criteria': {'field_name': 'sc_men', 'value': None},
                'chart_title_fields': ['Chart Field', 'Number of Schools'],
                'chart_data_fields': ['District',
                                      'No Men in Schools',
                                      'Men in Schools']
                },
              7: {'chart_label':  'Schools with Less than 4 Classrooms',
                  'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities',
                               'field_name': 'classrooms', 'value': 4, 'lt_operator': True},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'Schools with Less than 4 Classrooms',
                                        'Schools with More than 4 Classrooms']
                  },
              8: {'chart_label':  'Schools with at least 1 Open Air Class',
                  'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities',
                            'field_name':'openair_class' , 'value': 1},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'Schools with at least 1 Open Air Class',
                                        'Schools with No Open Air Class']
                  },
              9: {'chart_label':  'Schools with Less than 50 usable toilets',
                  'criteria': {FIELD_MODEL_LABEL: 'BasicFacilities', 'field_name': 'toilet_usable',
                               'value': 50, 'lt_operator': True},
                  'chart_title_fields': ['Chart Field', 'Number of Schools'],
                  'chart_data_fields': ['District',
                                        'Schools with Less than 50 usable toilets',
                                        'Schools with More than 50 usable toilets']
                  },
              10: {'chart_label':  'Schools with No Hockey Facility',
                   'criteria': {FIELD_MODEL_LABEL: 'SportsFacilities', 'field_name': 'hockey', 'value': None},
                   'chart_title_fields': ['Chart Field', 'Number of Schools'],
                   'chart_data_fields': ['District',
                                         'Schools with No Hockey Facility',
                                         'Schools have Hockey Facility']
                   },
              11: {'chart_label':  'School with Less than 100 Books',
                   'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities',
                                'field_name': 'total_books', 'value': 100,
                                'lt_operator': True},
                   'chart_title_fields': ['Chart Field', 'Number of Schools'],
                   'chart_data_fields': ['District',
                                         'Schools have Less than 100 Books',
                                         'Schools have More than 100 Books']
                   }}
              # 12: {'chart_label':  'Schools have No Labs',
              #      'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities',
              #                   'field_name': 'lab_exist', 'value': None},
              #      'chart_title_fields': ['Chart Field', 'Number of Schools'],
              #      'chart_data_fields': ['District',
              #                            'Schools have No Labs',
              #                            'Schools have Labs']},
              # 13: {'chart_label':  'No Internet',
              #      'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities', 'field_name': 'internet_morning', 'value': 1},
              #               {FIELD_MODEL_LABEL: 'AcademicFacilities', 'field_name': 'internet_evening', 'value': 1}}}
              # 14: {'chart_label':  'Labs with No Instruments',
              #  'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities', 'field_name': , 'value': None}},
              # 15: {'chart_label':  'No English Medium Students',
              #  'criteria': {FIELD_MODEL_LABEL: 'AcademicFacilities', 'field_name': , 'value': , 'lt_operator': True}}